### ISSUE TITLE
Running rbxmk causes panic for unresolved fragments

### ISSUE THREAD

**Issue by ayuka** [Anaminus/rbxmk#46] opened 2021-05-22 19:06 UTC
The executable panics every time I run it regardless of arguments passed.

I am running Windows 10 64-bit and trying to use the 0.7.1 executable. This does not happen when using the 0.6.2 executable.

Here is a text file containing what it prints out (I can post this in a reply, if you prefer): [rbxmk-output.txt](https://github.com/Anaminus/rbxmk/files/6526996/rbxmk-output.txt)

Edit: I just built from source and this still persisted. Let me know if you need any information about my system.

**Comment by Anaminus** [comment] 2021-05-23 17:49
Thanks for reporting this. The problem is fixed by a6db9a98736daa3f6004e28efe57790a6b9154c5, and I'll make a new release soon.

**Closed as completed by Anaminus** 2021-05-23 17:49 UTC
Labels: bug
