### ISSUE TITLE
Better support for reading models and saving to .rbxmx files

### ISSUE THREAD

**Issue by fredgig** [Anaminus/rbxmk#47] opened 2021-05-27 14:19 UTC
It seems like rbxmk doesn't currently do a great job at saving models to .rbxmx files. Attempting to import into Roblox Studio a .rbxmx generated by rbxmk will be unsuccessful.

I don't know if this is a known issue due to technical limitations, but here is how I am able to fix a corrupted .rbxmx file, even for somewhat complex models.

1. For tags containing an asset URL, wrap the url inside a <url> tag:

```
BEFORE:

<string name="PROPERTY">rbxassetid://ASSET_ID</string>

AFTER:

<string name="PROPERTY"><url>rbxassetid://ASSET_ID</url></string>
```

2. Enter the appropriate value inside the ModelMeshData. Not sure how this is found programmatically, but I get it from a .rbxmx file that was directly exported from Roblox Studio.

```
BEFORE:

<SharedString name="ModelMeshData"></SharedString>

AFTER:

<SharedString name="ModelMeshData">**MODEL_MESH_DATA_STRING**</SharedString>
```

3. PhysicalConfigData does not seem to contain a valid value. In the same manner as the previous fix for ModelMeshData, I get the tag value from a .rbxmx exported from Studio.

```
BEFORE:

<SharedString name="PhysicalConfigData"><![CDATA[**SOME_CDATA_STRING**]]></SharedString>

AFTER:

<SharedString name="PhysicalConfigData">**PHYSICAL_CONFIG_DATA_STRING**</SharedString>
```

4. Finally, at the bottom of the .rbxmx file, add a new set of tags to reference to **MODEL_MESH_DATA_STRING**, **PHYSICAL_CONFIG_DATA_STRING** and **SOME_CDATA_STRING**.

```
<SharedStrings>	
	<SharedString md5="**MODEL_MESH_DATA_STRING**"></SharedString>	
	<SharedString md5="**PHYSICAL_CONFIG_DATA_STRING**">**SOME_CDATA_STRING**</SharedString>	
</SharedStrings>
```

**Comment by Anaminus** [comment] 2021-05-27 19:28
For properties that should have the Content type, make sure you wrap the value in a Content [exprim](https://github.com/Anaminus/rbxmk/blob/v0.7.2/doc/README.md#explicit-primitives):

```lua
decal.Texture = types.Content("rbxassetid://ASSET_ID")
```

Alternatively, having a [descriptor](https://github.com/Anaminus/rbxmk/blob/v0.7.2/doc/README.md#descriptors) specified will do this conversion automatically. The easiest way is to include one of the [descriptor flags](https://github.com/Anaminus/rbxmk/blob/v0.7.2/fragments/en-us/flags/desc.md) when running a script:

```bash
# Download the latest API dump and use as rbxmk.globalDesc
rbxmk run --desc-latest script.lua
```

As for the SharedString type, this seems to be a problem with [rbxfile](https://github.com/RobloxAPI/rbxfile), which I'll look into.

**Comment by Anaminus** [comment] 2021-05-27 23:12
SharedStrings should be fixed, and will be available in the next release.

**Closed as completed by Anaminus** 2021-05-27 23:12 UTC
Labels: bug

**Comment by fredgig** [comment] 2021-05-28 15:42
> For properties that should have the Content type, make sure you wrap the value in a Content [exprim](https://github.com/Anaminus/rbxmk/blob/v0.7.2/doc/README.md#explicit-primitives):
> 
> ```lua
> decal.Texture = types.Content("rbxassetid://ASSET_ID")
> ```
> 
> Alternatively, having a [descriptor](https://github.com/Anaminus/rbxmk/blob/v0.7.2/doc/README.md#descriptors) specified will do this conversion automatically. The easiest way is to include one of the [descriptor flags](https://github.com/Anaminus/rbxmk/blob/v0.7.2/fragments/en-us/flags/desc.md) when running a script:

Looking back at this, I don't think this was fully relevant to my issue, which I failed to put into context.

The issue arises when reading models/instances from a .rbxl file and exporting each individual model/instance as a .rbxml file. Am I wrong to think that I should not have to do actions like wrapping values? Should I still use descriptors for this?

**Comment by Anaminus** [comment] 2021-05-28 16:04
This is a known issue. rbxl stores all string-like values as strings, so a descriptor is required to convert these values back to their expected types.

However, even with a descriptor specified, it still wont work. The problem is that the rbx formats do not use descriptors when decoding or encoding types. My plan to fix this is to add a "Desc" option to each rbx format that allows a descriptor to be specified. Additionally, they will fall back to globalDesc if needed.

But yes, a descriptor will always be required to properly convert rbxl to rbxlx, because rbxl does not include information for certain types. I'll make a separate issue to track the progress of descriptors for the rbx formats.

**Comment by fredgig** [comment] 2021-05-28 16:10
Got it, I'll keep an eye out for an update. Thanks again.

**Comment by Anaminus** [comment] 2021-05-31 16:59
So bb154a5469efe3bd5026d6a0190981c6e255e8b7 makes changes to do a lot more to handle value conversions. For example, if the descriptor says a property is of the Content type, then any string-like value will be converted to Content. I also added the [DescMode](https://github.com/Anaminus/rbxmk/blob/imperative/doc/formats.md#user-content-rbxl) format option to determine the strictness of these conversions.

There is still a caveat, which is that Roblox's API dumps do not include certain serialized properties. I've already anticipated this problem with a system that allows patching of descriptor files. This makes it easy to download the latest API dump and then apply a locally maintained patch.

For example, I have this patch file saved as `dump.desc-patch.json`:
```json
[
	{
		"Type": 1,
		"Element": "Property",
		"Primary": "Instance",
		"Secondary": "AttributesSerialize",
		"Fields": {
			"CanLoad": true,
			"CanSave": true,
			"Category": "Data",
			"Name": "AttributesSerialize",
			"ReadSecurity": "None",
			"Tags": [
				"NotScriptable"
			],
			"ValueType": {
				"Category": "DataType",
				"Name": "BinaryString"
			},
			"WriteSecurity": "None"
		}
	},
	{
		"Type": 1,
		"Element": "Property",
		"Primary": "Instance",
		"Secondary": "Tags",
		"Fields": {
			"CanLoad": true,
			"CanSave": true,
			"Category": "Data",
			"Name": "Tags",
			"ReadSecurity": "None",
			"Tags": [
				"NotScriptable"
			],
			"ValueType": {
				"Category": "DataType",
				"Name": "BinaryString"
			},
			"WriteSecurity": "None"
		}
	}
]
```

The command to download the latest dump and apply this patch might look like this:
```bash
rbxmk --desc-latest --desc-patch dump.desc-patch.json script.lua
```

Or, patching it dynamically from within the script could be done like this:
```lua
rbxmk.patchDesc(rbxmk.globalDesc, fs.read("dump.desc-patch.json"))
```

**Comment by fredgig** [comment] 2021-06-02 19:55
I will mess around with this in the coming days and let you know how it goes.
